// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatproto.proto

/*
Package chat is a generated protocol buffer package.

It is generated from these files:
	chatproto.proto

It has these top-level messages:
	C2GIMMessage
	G2CIMMessage
	G2CIMChatResult
*/
package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatChannel int32

const (
	ChatChannel_NOCHANNEL    ChatChannel = 0
	ChatChannel_USERCHANNEL  ChatChannel = 1
	ChatChannel_WORLDCHANNEL ChatChannel = 2
	ChatChannel_ALLCHANNEL   ChatChannel = 255
)

var ChatChannel_name = map[int32]string{
	0:   "NOCHANNEL",
	1:   "USERCHANNEL",
	2:   "WORLDCHANNEL",
	255: "ALLCHANNEL",
}
var ChatChannel_value = map[string]int32{
	"NOCHANNEL":    0,
	"USERCHANNEL":  1,
	"WORLDCHANNEL": 2,
	"ALLCHANNEL":   255,
}

func (x ChatChannel) String() string {
	return proto.EnumName(ChatChannel_name, int32(x))
}
func (ChatChannel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type C2GIMMessage_MsgID int32

const (
	C2GIMMessage_Zero C2GIMMessage_MsgID = 0
	C2GIMMessage_ID   C2GIMMessage_MsgID = 90001
)

var C2GIMMessage_MsgID_name = map[int32]string{
	0:     "Zero",
	90001: "ID",
}
var C2GIMMessage_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   90001,
}

func (x C2GIMMessage_MsgID) String() string {
	return proto.EnumName(C2GIMMessage_MsgID_name, int32(x))
}
func (C2GIMMessage_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type G2CIMMessage_MsgID int32

const (
	G2CIMMessage_Zero G2CIMMessage_MsgID = 0
	G2CIMMessage_ID   G2CIMMessage_MsgID = 90002
)

var G2CIMMessage_MsgID_name = map[int32]string{
	0:     "Zero",
	90002: "ID",
}
var G2CIMMessage_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   90002,
}

func (x G2CIMMessage_MsgID) String() string {
	return proto.EnumName(G2CIMMessage_MsgID_name, int32(x))
}
func (G2CIMMessage_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type G2CIMChatResult_MsgID int32

const (
	G2CIMChatResult_Zero G2CIMChatResult_MsgID = 0
	G2CIMChatResult_ID   G2CIMChatResult_MsgID = 90003
)

var G2CIMChatResult_MsgID_name = map[int32]string{
	0:     "Zero",
	90003: "ID",
}
var G2CIMChatResult_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   90003,
}

func (x G2CIMChatResult_MsgID) String() string {
	return proto.EnumName(G2CIMChatResult_MsgID_name, int32(x))
}
func (G2CIMChatResult_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// start 90001
type C2GIMMessage struct {
	Touser  uint64 `protobuf:"varint,1,opt,name=touser" json:"touser,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Channel uint32 `protobuf:"varint,3,opt,name=channel" json:"channel,omitempty"`
}

func (m *C2GIMMessage) Reset()                    { *m = C2GIMMessage{} }
func (m *C2GIMMessage) String() string            { return proto.CompactTextString(m) }
func (*C2GIMMessage) ProtoMessage()               {}
func (*C2GIMMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2GIMMessage) GetTouser() uint64 {
	if m != nil {
		return m.Touser
	}
	return 0
}

func (m *C2GIMMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *C2GIMMessage) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

type G2CIMMessage struct {
	From    uint64 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Channel uint32 `protobuf:"varint,3,opt,name=channel" json:"channel,omitempty"`
}

func (m *G2CIMMessage) Reset()                    { *m = G2CIMMessage{} }
func (m *G2CIMMessage) String() string            { return proto.CompactTextString(m) }
func (*G2CIMMessage) ProtoMessage()               {}
func (*G2CIMMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *G2CIMMessage) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *G2CIMMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *G2CIMMessage) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

type G2CIMChatResult struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *G2CIMChatResult) Reset()                    { *m = G2CIMChatResult{} }
func (m *G2CIMChatResult) String() string            { return proto.CompactTextString(m) }
func (*G2CIMChatResult) ProtoMessage()               {}
func (*G2CIMChatResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *G2CIMChatResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*C2GIMMessage)(nil), "chat.C2GIMMessage")
	proto.RegisterType((*G2CIMMessage)(nil), "chat.G2CIMMessage")
	proto.RegisterType((*G2CIMChatResult)(nil), "chat.G2CIMChatResult")
	proto.RegisterEnum("chat.ChatChannel", ChatChannel_name, ChatChannel_value)
	proto.RegisterEnum("chat.C2GIMMessage_MsgID", C2GIMMessage_MsgID_name, C2GIMMessage_MsgID_value)
	proto.RegisterEnum("chat.G2CIMMessage_MsgID", G2CIMMessage_MsgID_name, G2CIMMessage_MsgID_value)
	proto.RegisterEnum("chat.G2CIMChatResult_MsgID", G2CIMChatResult_MsgID_name, G2CIMChatResult_MsgID_value)
}

func init() { proto.RegisterFile("chatproto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc6, 0x97, 0xda, 0xce, 0xf5, 0xbf, 0x8e, 0x96, 0xff, 0x41, 0x0a, 0x5e, 0x4a, 0x4f, 0xc5,
	0x83, 0x87, 0xf9, 0x04, 0x23, 0x9d, 0xb3, 0xd0, 0x76, 0x12, 0x11, 0xc1, 0x5b, 0x1d, 0x71, 0x3d,
	0xcc, 0x46, 0x92, 0x0c, 0x9f, 0x43, 0x7d, 0xa0, 0x3e, 0x9a, 0xd2, 0xd8, 0xe0, 0xc9, 0x9b, 0x97,
	0xf0, 0xfd, 0xbe, 0xc0, 0xf7, 0x23, 0x04, 0xc2, 0x5d, 0xdb, 0xe8, 0x57, 0x29, 0xb4, 0xb8, 0x34,
	0x27, 0xba, 0x43, 0x91, 0xbe, 0x41, 0x40, 0x97, 0x9b, 0xa2, 0xaa, 0xb8, 0x52, 0xcd, 0x9e, 0xe3,
	0x19, 0x4c, 0xb5, 0x38, 0x2a, 0x2e, 0x63, 0x92, 0x90, 0xcc, 0x65, 0x23, 0x61, 0x0c, 0xa7, 0x3b,
	0xd1, 0x69, 0xde, 0xe9, 0xd8, 0x49, 0x48, 0xe6, 0x33, 0x8b, 0xe6, 0xa6, 0x6d, 0xba, 0x8e, 0x1f,
	0xe2, 0x93, 0x84, 0x64, 0x0b, 0x66, 0x31, 0x3d, 0x07, 0xaf, 0x52, 0xfb, 0x22, 0xc7, 0x19, 0xb8,
	0x8f, 0x5c, 0x8a, 0x68, 0x82, 0x33, 0x70, 0x8a, 0x3c, 0x7a, 0xef, 0xbd, 0x54, 0x41, 0xb0, 0x59,
	0xd2, 0x5f, 0x31, 0x82, 0xfb, 0x2c, 0xc5, 0xcb, 0xa8, 0x35, 0xf9, 0x7f, 0xa5, 0x1f, 0xbd, 0x97,
	0x5e, 0x43, 0x68, 0xa4, 0xb4, 0x6d, 0x34, 0xe3, 0xea, 0x78, 0xd0, 0xc3, 0x83, 0xa5, 0x49, 0xc6,
	0xec, 0xb3, 0x91, 0xfe, 0xde, 0xf9, 0xec, 0xbd, 0x8b, 0x5b, 0x98, 0x0f, 0x13, 0xf4, 0xc7, 0x89,
	0x0b, 0xf0, 0xeb, 0x2d, 0xbd, 0x59, 0xd5, 0xf5, 0xba, 0x8c, 0x26, 0x18, 0xc2, 0xfc, 0xfe, 0x6e,
	0xcd, 0x6c, 0x41, 0x30, 0x82, 0xe0, 0x61, 0xcb, 0xca, 0xdc, 0x36, 0x0e, 0x86, 0x00, 0xab, 0xb2,
	0xb4, 0xfc, 0x45, 0x9e, 0xa6, 0xe6, 0x53, 0xae, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x12, 0x61,
	0xa2, 0x5d, 0xa7, 0x01, 0x00, 0x00,
}
