// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	gateway.proto
	login.proto
	service.proto

It has these top-level messages:
	Gateway
	G2CRegisterGateway
	C2GRegisterGatewayResult
	G2CRegisterGatewayUser
	C2GRegisterGatewayUserResult
	G2CRemoveGatewayUser
	C2GAddServiceServer
	C2GRemoveServiceServere
	C2LRegister
	L2CRegisterResult
	C2LLogin
	C2LLoginThirdSDK
	L2CLoginResult
	C2GTokenLogin
	G2CTokenLoginResult
	Service
	S2CServiceRegister
	C2SServiceRegisterResult
	C2GServiceRegister
	C2GServiceRemove
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type G2CRegisterGateway_MsgID int32

const (
	G2CRegisterGateway_Zero G2CRegisterGateway_MsgID = 0
	G2CRegisterGateway_ID   G2CRegisterGateway_MsgID = 1
)

var G2CRegisterGateway_MsgID_name = map[int32]string{
	0: "Zero",
	1: "ID",
}
var G2CRegisterGateway_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   1,
}

func (x G2CRegisterGateway_MsgID) String() string {
	return proto.EnumName(G2CRegisterGateway_MsgID_name, int32(x))
}
func (G2CRegisterGateway_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type C2GRegisterGatewayResult_MsgID int32

const (
	C2GRegisterGatewayResult_Zero C2GRegisterGatewayResult_MsgID = 0
	C2GRegisterGatewayResult_ID   C2GRegisterGatewayResult_MsgID = 2
)

var C2GRegisterGatewayResult_MsgID_name = map[int32]string{
	0: "Zero",
	2: "ID",
}
var C2GRegisterGatewayResult_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   2,
}

func (x C2GRegisterGatewayResult_MsgID) String() string {
	return proto.EnumName(C2GRegisterGatewayResult_MsgID_name, int32(x))
}
func (C2GRegisterGatewayResult_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type G2CRegisterGatewayUser_MsgID int32

const (
	G2CRegisterGatewayUser_Zero G2CRegisterGatewayUser_MsgID = 0
	G2CRegisterGatewayUser_ID   G2CRegisterGatewayUser_MsgID = 3
)

var G2CRegisterGatewayUser_MsgID_name = map[int32]string{
	0: "Zero",
	3: "ID",
}
var G2CRegisterGatewayUser_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   3,
}

func (x G2CRegisterGatewayUser_MsgID) String() string {
	return proto.EnumName(G2CRegisterGatewayUser_MsgID_name, int32(x))
}
func (G2CRegisterGatewayUser_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type C2GRegisterGatewayUserResult_MsgID int32

const (
	C2GRegisterGatewayUserResult_Zero C2GRegisterGatewayUserResult_MsgID = 0
	C2GRegisterGatewayUserResult_ID   C2GRegisterGatewayUserResult_MsgID = 4
)

var C2GRegisterGatewayUserResult_MsgID_name = map[int32]string{
	0: "Zero",
	4: "ID",
}
var C2GRegisterGatewayUserResult_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   4,
}

func (x C2GRegisterGatewayUserResult_MsgID) String() string {
	return proto.EnumName(C2GRegisterGatewayUserResult_MsgID_name, int32(x))
}
func (C2GRegisterGatewayUserResult_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type G2CRemoveGatewayUser_MsgID int32

const (
	G2CRemoveGatewayUser_Zero G2CRemoveGatewayUser_MsgID = 0
	G2CRemoveGatewayUser_ID   G2CRemoveGatewayUser_MsgID = 5
)

var G2CRemoveGatewayUser_MsgID_name = map[int32]string{
	0: "Zero",
	5: "ID",
}
var G2CRemoveGatewayUser_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   5,
}

func (x G2CRemoveGatewayUser_MsgID) String() string {
	return proto.EnumName(G2CRemoveGatewayUser_MsgID_name, int32(x))
}
func (G2CRemoveGatewayUser_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type C2GAddServiceServer_MsgID int32

const (
	C2GAddServiceServer_Zero C2GAddServiceServer_MsgID = 0
	C2GAddServiceServer_ID   C2GAddServiceServer_MsgID = 6
)

var C2GAddServiceServer_MsgID_name = map[int32]string{
	0: "Zero",
	6: "ID",
}
var C2GAddServiceServer_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   6,
}

func (x C2GAddServiceServer_MsgID) String() string {
	return proto.EnumName(C2GAddServiceServer_MsgID_name, int32(x))
}
func (C2GAddServiceServer_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type C2GRemoveServiceServere_MsgID int32

const (
	C2GRemoveServiceServere_Zero C2GRemoveServiceServere_MsgID = 0
	C2GRemoveServiceServere_ID   C2GRemoveServiceServere_MsgID = 7
)

var C2GRemoveServiceServere_MsgID_name = map[int32]string{
	0: "Zero",
	7: "ID",
}
var C2GRemoveServiceServere_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   7,
}

func (x C2GRemoveServiceServere_MsgID) String() string {
	return proto.EnumName(C2GRemoveServiceServere_MsgID_name, int32(x))
}
func (C2GRemoveServiceServere_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

type Gateway struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Gateway) Reset()                    { *m = Gateway{} }
func (m *Gateway) String() string            { return proto.CompactTextString(m) }
func (*Gateway) ProtoMessage()               {}
func (*Gateway) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Gateway) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Gateway) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type G2CRegisterGateway struct {
	Gate *Gateway `protobuf:"bytes,1,opt,name=gate" json:"gate,omitempty"`
}

func (m *G2CRegisterGateway) Reset()                    { *m = G2CRegisterGateway{} }
func (m *G2CRegisterGateway) String() string            { return proto.CompactTextString(m) }
func (*G2CRegisterGateway) ProtoMessage()               {}
func (*G2CRegisterGateway) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *G2CRegisterGateway) GetGate() *Gateway {
	if m != nil {
		return m.Gate
	}
	return nil
}

type C2GRegisterGatewayResult struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *C2GRegisterGatewayResult) Reset()                    { *m = C2GRegisterGatewayResult{} }
func (m *C2GRegisterGatewayResult) String() string            { return proto.CompactTextString(m) }
func (*C2GRegisterGatewayResult) ProtoMessage()               {}
func (*C2GRegisterGatewayResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *C2GRegisterGatewayResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type G2CRegisterGatewayUser struct {
	Uid uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *G2CRegisterGatewayUser) Reset()                    { *m = G2CRegisterGatewayUser{} }
func (m *G2CRegisterGatewayUser) String() string            { return proto.CompactTextString(m) }
func (*G2CRegisterGatewayUser) ProtoMessage()               {}
func (*G2CRegisterGatewayUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *G2CRegisterGatewayUser) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type C2GRegisterGatewayUserResult struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *C2GRegisterGatewayUserResult) Reset()                    { *m = C2GRegisterGatewayUserResult{} }
func (m *C2GRegisterGatewayUserResult) String() string            { return proto.CompactTextString(m) }
func (*C2GRegisterGatewayUserResult) ProtoMessage()               {}
func (*C2GRegisterGatewayUserResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *C2GRegisterGatewayUserResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type G2CRemoveGatewayUser struct {
	Uid uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *G2CRemoveGatewayUser) Reset()                    { *m = G2CRemoveGatewayUser{} }
func (m *G2CRemoveGatewayUser) String() string            { return proto.CompactTextString(m) }
func (*G2CRemoveGatewayUser) ProtoMessage()               {}
func (*G2CRemoveGatewayUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *G2CRemoveGatewayUser) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// 业务处理的设计，就是一个rpc服务器，gateway通过rpc调用，处理这个消息，然后，可以在rpc返回给这次调用的结果。如果需要转给其他客户端，通过centerserver转交
// 增加一个业务处理服务器
type C2GAddServiceServer struct {
	ProcID     []int32 `protobuf:"varint,1,rep,packed,name=procID" json:"procID,omitempty"`
	RpcAddress string  `protobuf:"bytes,2,opt,name=rpcAddress" json:"rpcAddress,omitempty"`
}

func (m *C2GAddServiceServer) Reset()                    { *m = C2GAddServiceServer{} }
func (m *C2GAddServiceServer) String() string            { return proto.CompactTextString(m) }
func (*C2GAddServiceServer) ProtoMessage()               {}
func (*C2GAddServiceServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *C2GAddServiceServer) GetProcID() []int32 {
	if m != nil {
		return m.ProcID
	}
	return nil
}

func (m *C2GAddServiceServer) GetRpcAddress() string {
	if m != nil {
		return m.RpcAddress
	}
	return ""
}

// 删除一个业务处理服务器
type C2GRemoveServiceServere struct {
	Rpcadds string `protobuf:"bytes,3,opt,name=rpcadds" json:"rpcadds,omitempty"`
}

func (m *C2GRemoveServiceServere) Reset()                    { *m = C2GRemoveServiceServere{} }
func (m *C2GRemoveServiceServere) String() string            { return proto.CompactTextString(m) }
func (*C2GRemoveServiceServere) ProtoMessage()               {}
func (*C2GRemoveServiceServere) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *C2GRemoveServiceServere) GetRpcadds() string {
	if m != nil {
		return m.Rpcadds
	}
	return ""
}

func init() {
	proto.RegisterType((*Gateway)(nil), "protocol.Gateway")
	proto.RegisterType((*G2CRegisterGateway)(nil), "protocol.G2CRegisterGateway")
	proto.RegisterType((*C2GRegisterGatewayResult)(nil), "protocol.C2GRegisterGatewayResult")
	proto.RegisterType((*G2CRegisterGatewayUser)(nil), "protocol.G2CRegisterGatewayUser")
	proto.RegisterType((*C2GRegisterGatewayUserResult)(nil), "protocol.C2GRegisterGatewayUserResult")
	proto.RegisterType((*G2CRemoveGatewayUser)(nil), "protocol.G2CRemoveGatewayUser")
	proto.RegisterType((*C2GAddServiceServer)(nil), "protocol.C2GAddServiceServer")
	proto.RegisterType((*C2GRemoveServiceServere)(nil), "protocol.C2GRemoveServiceServere")
	proto.RegisterEnum("protocol.G2CRegisterGateway_MsgID", G2CRegisterGateway_MsgID_name, G2CRegisterGateway_MsgID_value)
	proto.RegisterEnum("protocol.C2GRegisterGatewayResult_MsgID", C2GRegisterGatewayResult_MsgID_name, C2GRegisterGatewayResult_MsgID_value)
	proto.RegisterEnum("protocol.G2CRegisterGatewayUser_MsgID", G2CRegisterGatewayUser_MsgID_name, G2CRegisterGatewayUser_MsgID_value)
	proto.RegisterEnum("protocol.C2GRegisterGatewayUserResult_MsgID", C2GRegisterGatewayUserResult_MsgID_name, C2GRegisterGatewayUserResult_MsgID_value)
	proto.RegisterEnum("protocol.G2CRemoveGatewayUser_MsgID", G2CRemoveGatewayUser_MsgID_name, G2CRemoveGatewayUser_MsgID_value)
	proto.RegisterEnum("protocol.C2GAddServiceServer_MsgID", C2GAddServiceServer_MsgID_name, C2GAddServiceServer_MsgID_value)
	proto.RegisterEnum("protocol.C2GRemoveServiceServere_MsgID", C2GRemoveServiceServere_MsgID_name, C2GRemoveServiceServere_MsgID_value)
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xfc, 0x6d, 0x3b, 0x2f, 0x4a, 0x5d, 0xa5, 0xae, 0x20, 0x52, 0x16, 0x84, 0x9e,
	0x72, 0x48, 0x3f, 0x41, 0x49, 0x24, 0xe4, 0x50, 0xc1, 0x15, 0x3d, 0x78, 0x8b, 0xd9, 0x21, 0x06,
	0x2a, 0x1b, 0x76, 0xd3, 0x8a, 0xdf, 0x5e, 0x76, 0x9b, 0x80, 0xb5, 0xe4, 0xd2, 0xd3, 0xcc, 0x93,
	0x49, 0x9e, 0xe7, 0x97, 0xdd, 0x81, 0xb3, 0xaa, 0x68, 0xf1, 0xab, 0xf8, 0x8e, 0x1a, 0x25, 0x5b,
	0x49, 0xc6, 0xb6, 0x94, 0x72, 0xc3, 0x96, 0x30, 0xca, 0xf6, 0x23, 0x72, 0x0e, 0x6e, 0x2d, 0xa8,
	0x33, 0x77, 0x16, 0x01, 0x77, 0x6b, 0x41, 0x28, 0x8c, 0x0a, 0x21, 0x14, 0x6a, 0x4d, 0xdd, 0xb9,
	0xb3, 0x98, 0xf0, 0x5e, 0xb2, 0x57, 0x20, 0x59, 0x9c, 0x70, 0xac, 0x6a, 0xdd, 0xa2, 0xea, 0xbf,
	0xbf, 0x07, 0xdf, 0xa4, 0x58, 0x87, 0xff, 0xf1, 0x45, 0xd4, 0x67, 0x44, 0xdd, 0x0b, 0xdc, 0x8e,
	0xd9, 0x0d, 0x04, 0x6b, 0x5d, 0xe5, 0x29, 0x19, 0x83, 0xff, 0x86, 0x4a, 0x4e, 0xff, 0x91, 0x10,
	0xdc, 0x3c, 0x9d, 0x3a, 0x6c, 0x0d, 0x34, 0x89, 0xb3, 0x3f, 0xbe, 0x1c, 0xf5, 0x76, 0xd3, 0x92,
	0x19, 0x84, 0xca, 0x76, 0xd6, 0x7f, 0xc2, 0x3b, 0x35, 0x6c, 0xe7, 0xb2, 0x07, 0x98, 0x1d, 0x63,
	0xbe, 0x68, 0x54, 0x64, 0x0a, 0xde, 0xb6, 0xfb, 0x57, 0x9f, 0x9b, 0x76, 0xd8, 0xc6, 0x63, 0x4f,
	0x70, 0x7b, 0x4c, 0x65, 0x6c, 0x4e, 0x25, 0xf3, 0x59, 0x02, 0x57, 0x96, 0xec, 0x53, 0xee, 0xf0,
	0x44, 0xae, 0x80, 0x7d, 0xc0, 0x65, 0x12, 0x67, 0x2b, 0x21, 0x9e, 0x51, 0xed, 0xea, 0x12, 0x4d,
	0x41, 0x65, 0x70, 0x1a, 0x25, 0xcb, 0x3c, 0xa5, 0xce, 0xdc, 0x5b, 0x04, 0xbc, 0x53, 0xe4, 0x0e,
	0x40, 0x35, 0xe5, 0xea, 0xe0, 0x46, 0x7f, 0x3d, 0x19, 0x4e, 0x0a, 0xd9, 0x23, 0x5c, 0xdb, 0x13,
	0x30, 0xb8, 0x07, 0x61, 0x68, 0x96, 0x44, 0x35, 0x65, 0x21, 0x84, 0xa6, 0xde, 0x7e, 0x49, 0x3a,
	0x39, 0xec, 0x37, 0x7a, 0x0f, 0xed, 0x6a, 0x2c, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xde,
	0x63, 0x2c, 0x96, 0x02, 0x00, 0x00,
}
