// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	C2LRegister
	L2CRegisterResult
	C2LLogin
	C2LLoginThirdSDK
	L2CLoginResult
	C2GTokenLogin
	G2CTokenLoginResult
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2LRegister_MsgID int32

const (
	C2LRegister_Zero C2LRegister_MsgID = 0
	C2LRegister_ID   C2LRegister_MsgID = 101
)

var C2LRegister_MsgID_name = map[int32]string{
	0:   "Zero",
	101: "ID",
}
var C2LRegister_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   101,
}

func (x C2LRegister_MsgID) String() string {
	return proto.EnumName(C2LRegister_MsgID_name, int32(x))
}
func (C2LRegister_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type L2CRegisterResult_MsgID int32

const (
	L2CRegisterResult_Zero L2CRegisterResult_MsgID = 0
	L2CRegisterResult_ID   L2CRegisterResult_MsgID = 102
)

var L2CRegisterResult_MsgID_name = map[int32]string{
	0:   "Zero",
	102: "ID",
}
var L2CRegisterResult_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   102,
}

func (x L2CRegisterResult_MsgID) String() string {
	return proto.EnumName(L2CRegisterResult_MsgID_name, int32(x))
}
func (L2CRegisterResult_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type C2LLogin_MsgID int32

const (
	C2LLogin_Zero C2LLogin_MsgID = 0
	C2LLogin_ID   C2LLogin_MsgID = 103
)

var C2LLogin_MsgID_name = map[int32]string{
	0:   "Zero",
	103: "ID",
}
var C2LLogin_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   103,
}

func (x C2LLogin_MsgID) String() string {
	return proto.EnumName(C2LLogin_MsgID_name, int32(x))
}
func (C2LLogin_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type C2LLoginThirdSDK_MsgID int32

const (
	C2LLoginThirdSDK_Zero C2LLoginThirdSDK_MsgID = 0
	C2LLoginThirdSDK_ID   C2LLoginThirdSDK_MsgID = 104
)

var C2LLoginThirdSDK_MsgID_name = map[int32]string{
	0:   "Zero",
	104: "ID",
}
var C2LLoginThirdSDK_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   104,
}

func (x C2LLoginThirdSDK_MsgID) String() string {
	return proto.EnumName(C2LLoginThirdSDK_MsgID_name, int32(x))
}
func (C2LLoginThirdSDK_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type L2CLoginResult_MsgID int32

const (
	L2CLoginResult_Zero L2CLoginResult_MsgID = 0
	L2CLoginResult_ID   L2CLoginResult_MsgID = 105
)

var L2CLoginResult_MsgID_name = map[int32]string{
	0:   "Zero",
	105: "ID",
}
var L2CLoginResult_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   105,
}

func (x L2CLoginResult_MsgID) String() string {
	return proto.EnumName(L2CLoginResult_MsgID_name, int32(x))
}
func (L2CLoginResult_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type C2GTokenLogin_MsgID int32

const (
	C2GTokenLogin_Zero C2GTokenLogin_MsgID = 0
	C2GTokenLogin_ID   C2GTokenLogin_MsgID = 106
)

var C2GTokenLogin_MsgID_name = map[int32]string{
	0:   "Zero",
	106: "ID",
}
var C2GTokenLogin_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   106,
}

func (x C2GTokenLogin_MsgID) String() string {
	return proto.EnumName(C2GTokenLogin_MsgID_name, int32(x))
}
func (C2GTokenLogin_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type G2CTokenLoginResult_MsgID int32

const (
	G2CTokenLoginResult_Zero G2CTokenLoginResult_MsgID = 0
	G2CTokenLoginResult_ID   G2CTokenLoginResult_MsgID = 107
)

var G2CTokenLoginResult_MsgID_name = map[int32]string{
	0:   "Zero",
	107: "ID",
}
var G2CTokenLoginResult_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   107,
}

func (x G2CTokenLoginResult_MsgID) String() string {
	return proto.EnumName(G2CTokenLoginResult_MsgID_name, int32(x))
}
func (G2CTokenLoginResult_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

// 101-200
// 注册，登录 到loginserver
type C2LRegister struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *C2LRegister) Reset()                    { *m = C2LRegister{} }
func (m *C2LRegister) String() string            { return proto.CompactTextString(m) }
func (*C2LRegister) ProtoMessage()               {}
func (*C2LRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2LRegister) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *C2LRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type L2CRegisterResult struct {
	Result      string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Token       string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	GatewayAddr string `protobuf:"bytes,3,opt,name=gatewayAddr" json:"gatewayAddr,omitempty"`
}

func (m *L2CRegisterResult) Reset()                    { *m = L2CRegisterResult{} }
func (m *L2CRegisterResult) String() string            { return proto.CompactTextString(m) }
func (*L2CRegisterResult) ProtoMessage()               {}
func (*L2CRegisterResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *L2CRegisterResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *L2CRegisterResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *L2CRegisterResult) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

type C2LLogin struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *C2LLogin) Reset()                    { *m = C2LLogin{} }
func (m *C2LLogin) String() string            { return proto.CompactTextString(m) }
func (*C2LLogin) ProtoMessage()               {}
func (*C2LLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *C2LLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *C2LLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 第三方登录
type C2LLoginThirdSDK struct {
	Platform  int32  `protobuf:"varint,1,opt,name=platform" json:"platform,omitempty"`
	SdkToken  string `protobuf:"bytes,2,opt,name=sdkToken" json:"sdkToken,omitempty"`
	SdkExtern string `protobuf:"bytes,3,opt,name=sdkExtern" json:"sdkExtern,omitempty"`
}

func (m *C2LLoginThirdSDK) Reset()                    { *m = C2LLoginThirdSDK{} }
func (m *C2LLoginThirdSDK) String() string            { return proto.CompactTextString(m) }
func (*C2LLoginThirdSDK) ProtoMessage()               {}
func (*C2LLoginThirdSDK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *C2LLoginThirdSDK) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *C2LLoginThirdSDK) GetSdkToken() string {
	if m != nil {
		return m.SdkToken
	}
	return ""
}

func (m *C2LLoginThirdSDK) GetSdkExtern() string {
	if m != nil {
		return m.SdkExtern
	}
	return ""
}

type L2CLoginResult struct {
	Result      string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Token       string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	GatewayAddr string `protobuf:"bytes,3,opt,name=gatewayAddr" json:"gatewayAddr,omitempty"`
}

func (m *L2CLoginResult) Reset()                    { *m = L2CLoginResult{} }
func (m *L2CLoginResult) String() string            { return proto.CompactTextString(m) }
func (*L2CLoginResult) ProtoMessage()               {}
func (*L2CLoginResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *L2CLoginResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *L2CLoginResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *L2CLoginResult) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

// 根据token登录到gateway
type C2GTokenLogin struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *C2GTokenLogin) Reset()                    { *m = C2GTokenLogin{} }
func (m *C2GTokenLogin) String() string            { return proto.CompactTextString(m) }
func (*C2GTokenLogin) ProtoMessage()               {}
func (*C2GTokenLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *C2GTokenLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type G2CTokenLoginResult struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Uid    uint64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
}

func (m *G2CTokenLoginResult) Reset()                    { *m = G2CTokenLoginResult{} }
func (m *G2CTokenLoginResult) String() string            { return proto.CompactTextString(m) }
func (*G2CTokenLoginResult) ProtoMessage()               {}
func (*G2CTokenLoginResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *G2CTokenLoginResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *G2CTokenLoginResult) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterType((*C2LRegister)(nil), "protocol.C2LRegister")
	proto.RegisterType((*L2CRegisterResult)(nil), "protocol.L2CRegisterResult")
	proto.RegisterType((*C2LLogin)(nil), "protocol.C2LLogin")
	proto.RegisterType((*C2LLoginThirdSDK)(nil), "protocol.C2LLoginThirdSDK")
	proto.RegisterType((*L2CLoginResult)(nil), "protocol.L2CLoginResult")
	proto.RegisterType((*C2GTokenLogin)(nil), "protocol.C2GTokenLogin")
	proto.RegisterType((*G2CTokenLoginResult)(nil), "protocol.G2CTokenLoginResult")
	proto.RegisterEnum("protocol.C2LRegister_MsgID", C2LRegister_MsgID_name, C2LRegister_MsgID_value)
	proto.RegisterEnum("protocol.L2CRegisterResult_MsgID", L2CRegisterResult_MsgID_name, L2CRegisterResult_MsgID_value)
	proto.RegisterEnum("protocol.C2LLogin_MsgID", C2LLogin_MsgID_name, C2LLogin_MsgID_value)
	proto.RegisterEnum("protocol.C2LLoginThirdSDK_MsgID", C2LLoginThirdSDK_MsgID_name, C2LLoginThirdSDK_MsgID_value)
	proto.RegisterEnum("protocol.L2CLoginResult_MsgID", L2CLoginResult_MsgID_name, L2CLoginResult_MsgID_value)
	proto.RegisterEnum("protocol.C2GTokenLogin_MsgID", C2GTokenLogin_MsgID_name, C2GTokenLogin_MsgID_value)
	proto.RegisterEnum("protocol.G2CTokenLoginResult_MsgID", G2CTokenLoginResult_MsgID_name, G2CTokenLoginResult_MsgID_value)
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcf, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xbf, 0xdd, 0x2f, 0xba, 0x77, 0x7c, 0xa5, 0x46, 0x91, 0x2a, 0x1e, 0x46, 0x4e, 0x9e,
	0x3c, 0xc4, 0x7f, 0x40, 0x49, 0x65, 0x0c, 0xeb, 0xa5, 0xee, 0x34, 0x10, 0xac, 0x26, 0xeb, 0x6a,
	0xbb, 0x66, 0x24, 0x29, 0x53, 0x04, 0x2f, 0xfe, 0xe3, 0xd2, 0xf4, 0xc7, 0x7a, 0x29, 0x5e, 0xc4,
	0x53, 0xf3, 0xe4, 0x81, 0xe7, 0xf3, 0x3e, 0x6f, 0x03, 0x93, 0x54, 0x44, 0x71, 0x76, 0xb9, 0x95,
	0x42, 0x0b, 0x64, 0x9b, 0xcf, 0x8b, 0x48, 0xf1, 0x13, 0x4c, 0x28, 0xf1, 0x03, 0x1e, 0xc5, 0x4a,
	0x73, 0x89, 0xce, 0xc0, 0xce, 0x15, 0x97, 0x59, 0xb8, 0xe1, 0xae, 0x35, 0xb5, 0x2e, 0xc6, 0x41,
	0xa3, 0x0b, 0x6f, 0x1b, 0x2a, 0xb5, 0x13, 0x92, 0xb9, 0xbd, 0xd2, 0xab, 0x35, 0x3e, 0x85, 0xe1,
	0xbd, 0x8a, 0xe6, 0x1e, 0xb2, 0x61, 0xb0, 0xe4, 0x52, 0x38, 0xff, 0xd0, 0x08, 0x7a, 0x73, 0xcf,
	0xe1, 0xf8, 0x13, 0x0e, 0x7d, 0x42, 0x6b, 0x42, 0xc0, 0x55, 0x9e, 0x6a, 0x74, 0x02, 0x23, 0x69,
	0x4e, 0x15, 0xa5, 0x52, 0xe8, 0x18, 0x86, 0x5a, 0x24, 0x3c, 0xab, 0x00, 0xa5, 0x40, 0x53, 0x98,
	0x44, 0xa1, 0xe6, 0xbb, 0xf0, 0xfd, 0x86, 0x31, 0xe9, 0xf6, 0x8d, 0xd7, 0xbe, 0xea, 0xe6, 0xaf,
	0xf0, 0x23, 0xd8, 0x94, 0xf8, 0x7e, 0xd1, 0xfe, 0xf7, 0xeb, 0x45, 0xf8, 0xcb, 0x02, 0xa7, 0xce,
	0x5f, 0xac, 0x63, 0xc9, 0x1e, 0xbc, 0x3b, 0x93, 0x95, 0x86, 0x7a, 0x25, 0xe4, 0xc6, 0x70, 0x86,
	0x41, 0xa3, 0x0b, 0x4f, 0xb1, 0x64, 0xd1, 0x6a, 0xd9, 0x68, 0x74, 0x0e, 0x63, 0xc5, 0x92, 0xdb,
	0x37, 0xcd, 0x65, 0x56, 0xd5, 0xdc, 0x5f, 0x74, 0x4f, 0xb1, 0xc6, 0x1f, 0x70, 0xe0, 0x13, 0x6a,
	0x86, 0xf8, 0xeb, 0x0d, 0xc7, 0xf8, 0x1a, 0xfe, 0x53, 0x32, 0x33, 0x0d, 0xca, 0x35, 0x37, 0x0c,
	0xab, 0xc5, 0xe8, 0x4e, 0x78, 0xc5, 0x4b, 0x38, 0x9a, 0x11, 0xba, 0x4f, 0xf8, 0xa1, 0x83, 0x03,
	0xfd, 0x3c, 0x2e, 0xff, 0xd2, 0x20, 0x28, 0x8e, 0xdd, 0xd9, 0xc9, 0xf3, 0xc8, 0xbc, 0xf5, 0xab,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x9d, 0xa9, 0x84, 0x01, 0x03, 0x00, 0x00,
}
