// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type S2CServiceRegister_MsgID int32

const (
	S2CServiceRegister_Zero S2CServiceRegister_MsgID = 0
	S2CServiceRegister_ID   S2CServiceRegister_MsgID = 201
)

var S2CServiceRegister_MsgID_name = map[int32]string{
	0:   "Zero",
	201: "ID",
}
var S2CServiceRegister_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   201,
}

func (x S2CServiceRegister_MsgID) String() string {
	return proto.EnumName(S2CServiceRegister_MsgID_name, int32(x))
}
func (S2CServiceRegister_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 0} }

type C2SServiceRegisterResult_MsgID int32

const (
	C2SServiceRegisterResult_Zero C2SServiceRegisterResult_MsgID = 0
	C2SServiceRegisterResult_ID   C2SServiceRegisterResult_MsgID = 202
)

var C2SServiceRegisterResult_MsgID_name = map[int32]string{
	0:   "Zero",
	202: "ID",
}
var C2SServiceRegisterResult_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   202,
}

func (x C2SServiceRegisterResult_MsgID) String() string {
	return proto.EnumName(C2SServiceRegisterResult_MsgID_name, int32(x))
}
func (C2SServiceRegisterResult_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{2, 0}
}

type C2GServiceRegister_MsgID int32

const (
	C2GServiceRegister_Zero C2GServiceRegister_MsgID = 0
	C2GServiceRegister_ID   C2GServiceRegister_MsgID = 203
)

var C2GServiceRegister_MsgID_name = map[int32]string{
	0:   "Zero",
	203: "ID",
}
var C2GServiceRegister_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   203,
}

func (x C2GServiceRegister_MsgID) String() string {
	return proto.EnumName(C2GServiceRegister_MsgID_name, int32(x))
}
func (C2GServiceRegister_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{3, 0} }

type C2GServiceRemove_MsgID int32

const (
	C2GServiceRemove_Zero C2GServiceRemove_MsgID = 0
	C2GServiceRemove_ID   C2GServiceRemove_MsgID = 204
)

var C2GServiceRemove_MsgID_name = map[int32]string{
	0:   "Zero",
	204: "ID",
}
var C2GServiceRemove_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   204,
}

func (x C2GServiceRemove_MsgID) String() string {
	return proto.EnumName(C2GServiceRemove_MsgID_name, int32(x))
}
func (C2GServiceRemove_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{4, 0} }

type Service struct {
	Handler []int32 `protobuf:"varint,1,rep,packed,name=handler" json:"handler,omitempty"`
	Version int32   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Name    string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Address string  `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Service) GetHandler() []int32 {
	if m != nil {
		return m.Handler
	}
	return nil
}

func (m *Service) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// service 2 center server 注册
type S2CServiceRegister struct {
	Serv *Service `protobuf:"bytes,1,opt,name=serv" json:"serv,omitempty"`
}

func (m *S2CServiceRegister) Reset()                    { *m = S2CServiceRegister{} }
func (m *S2CServiceRegister) String() string            { return proto.CompactTextString(m) }
func (*S2CServiceRegister) ProtoMessage()               {}
func (*S2CServiceRegister) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *S2CServiceRegister) GetServ() *Service {
	if m != nil {
		return m.Serv
	}
	return nil
}

// center 2 service 注册结果
type C2SServiceRegisterResult struct {
	Result string `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *C2SServiceRegisterResult) Reset()                    { *m = C2SServiceRegisterResult{} }
func (m *C2SServiceRegisterResult) String() string            { return proto.CompactTextString(m) }
func (*C2SServiceRegisterResult) ProtoMessage()               {}
func (*C2SServiceRegisterResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *C2SServiceRegisterResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// center 2 gateway 注册 service,广播
type C2GServiceRegister struct {
	Serv *Service `protobuf:"bytes,1,opt,name=serv" json:"serv,omitempty"`
}

func (m *C2GServiceRegister) Reset()                    { *m = C2GServiceRegister{} }
func (m *C2GServiceRegister) String() string            { return proto.CompactTextString(m) }
func (*C2GServiceRegister) ProtoMessage()               {}
func (*C2GServiceRegister) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *C2GServiceRegister) GetServ() *Service {
	if m != nil {
		return m.Serv
	}
	return nil
}

// center2 gateway 删除service ,广播
type C2GServiceRemove struct {
	Serv *Service `protobuf:"bytes,1,opt,name=serv" json:"serv,omitempty"`
}

func (m *C2GServiceRemove) Reset()                    { *m = C2GServiceRemove{} }
func (m *C2GServiceRemove) String() string            { return proto.CompactTextString(m) }
func (*C2GServiceRemove) ProtoMessage()               {}
func (*C2GServiceRemove) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *C2GServiceRemove) GetServ() *Service {
	if m != nil {
		return m.Serv
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "protocol.Service")
	proto.RegisterType((*S2CServiceRegister)(nil), "protocol.S2CServiceRegister")
	proto.RegisterType((*C2SServiceRegisterResult)(nil), "protocol.C2SServiceRegisterResult")
	proto.RegisterType((*C2GServiceRegister)(nil), "protocol.C2GServiceRegister")
	proto.RegisterType((*C2GServiceRemove)(nil), "protocol.C2GServiceRemove")
	proto.RegisterEnum("protocol.S2CServiceRegister_MsgID", S2CServiceRegister_MsgID_name, S2CServiceRegister_MsgID_value)
	proto.RegisterEnum("protocol.C2SServiceRegisterResult_MsgID", C2SServiceRegisterResult_MsgID_name, C2SServiceRegisterResult_MsgID_value)
	proto.RegisterEnum("protocol.C2GServiceRegister_MsgID", C2GServiceRegister_MsgID_name, C2GServiceRegister_MsgID_value)
	proto.RegisterEnum("protocol.C2GServiceRemove_MsgID", C2GServiceRemove_MsgID_name, C2GServiceRemove_MsgID_value)
}

func init() { proto.RegisterFile("service.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x8e, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9d, 0x36, 0x6d, 0xda, 0x11, 0x21, 0xce, 0x41, 0x16, 0x4f, 0x61, 0x41, 0xc8, 0x29,
	0x87, 0xf8, 0x11, 0x52, 0x90, 0x1e, 0xf4, 0xb0, 0x41, 0x04, 0x6f, 0xb1, 0x19, 0x6a, 0x30, 0xcd,
	0xca, 0x6e, 0xcc, 0x77, 0xf4, 0xcf, 0x87, 0x92, 0xdd, 0x24, 0x20, 0x82, 0x27, 0x7b, 0xda, 0x79,
	0xfb, 0x66, 0xde, 0xfb, 0xe1, 0x99, 0x65, 0xd3, 0xd7, 0x3b, 0x4e, 0x5f, 0x8d, 0xee, 0x34, 0xad,
	0xfc, 0xb3, 0xd3, 0x8d, 0x7c, 0xc1, 0xb0, 0x18, 0x2c, 0x12, 0x18, 0x3e, 0x97, 0x6d, 0xd5, 0xb0,
	0x11, 0x10, 0xcf, 0x93, 0x85, 0x9a, 0xa4, 0x73, 0x7a, 0x36, 0xb6, 0xd6, 0xad, 0x98, 0xc5, 0xe0,
	0x9c, 0x51, 0x12, 0x61, 0xd0, 0x96, 0x07, 0x16, 0xf3, 0x18, 0x92, 0xb5, 0xf2, 0xb3, 0xdb, 0x2e,
	0xab, 0xca, 0xb0, 0xb5, 0x22, 0xf0, 0xdf, 0x93, 0x94, 0x0f, 0x48, 0x45, 0x96, 0x8f, 0x7d, 0x8a,
	0xf7, 0xb5, 0xed, 0xd8, 0xd0, 0x15, 0x06, 0x8e, 0x4e, 0x40, 0x0c, 0xc9, 0x69, 0x76, 0x9e, 0x4e,
	0x6c, 0xe9, 0xb4, 0xe8, 0x6d, 0x79, 0x89, 0x8b, 0x5b, 0xbb, 0xdf, 0x6e, 0x68, 0x85, 0xc1, 0x23,
	0x1b, 0x1d, 0x9d, 0x50, 0x88, 0xb3, 0xed, 0x26, 0x7a, 0x07, 0x79, 0x87, 0x22, 0xcf, 0x8a, 0x5f,
	0xc1, 0x8a, 0xed, 0x5b, 0xd3, 0xd1, 0x05, 0x2e, 0x87, 0xc9, 0x17, 0xac, 0xd5, 0xa8, 0xfe, 0xce,
	0xfb, 0x00, 0x07, 0x9a, 0x67, 0x37, 0xc7, 0x06, 0xfd, 0x04, 0x79, 0x8f, 0xd1, 0xcf, 0xe0, 0x83,
	0xee, 0xf9, 0xdf, 0xb1, 0x5f, 0xf0, 0xb4, 0xf4, 0x37, 0xd7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xa8, 0xf7, 0x0e, 0x90, 0xe7, 0x01, 0x00, 0x00,
}
