// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type S2CServiceRegister_MsgID int32

const (
	S2CServiceRegister_Zero S2CServiceRegister_MsgID = 0
	S2CServiceRegister_ID   S2CServiceRegister_MsgID = 201
)

var S2CServiceRegister_MsgID_name = map[int32]string{
	0:   "Zero",
	201: "ID",
}
var S2CServiceRegister_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   201,
}

func (x S2CServiceRegister_MsgID) String() string {
	return proto.EnumName(S2CServiceRegister_MsgID_name, int32(x))
}
func (S2CServiceRegister_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 0} }

type C2SServiceRegisterResult_MsgID int32

const (
	C2SServiceRegisterResult_Zero C2SServiceRegisterResult_MsgID = 0
	C2SServiceRegisterResult_ID   C2SServiceRegisterResult_MsgID = 202
)

var C2SServiceRegisterResult_MsgID_name = map[int32]string{
	0:   "Zero",
	202: "ID",
}
var C2SServiceRegisterResult_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   202,
}

func (x C2SServiceRegisterResult_MsgID) String() string {
	return proto.EnumName(C2SServiceRegisterResult_MsgID_name, int32(x))
}
func (C2SServiceRegisterResult_MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{2, 0}
}

type C2GServiceRegister_MsgID int32

const (
	C2GServiceRegister_Zero C2GServiceRegister_MsgID = 0
	C2GServiceRegister_ID   C2GServiceRegister_MsgID = 203
)

var C2GServiceRegister_MsgID_name = map[int32]string{
	0:   "Zero",
	203: "ID",
}
var C2GServiceRegister_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   203,
}

func (x C2GServiceRegister_MsgID) String() string {
	return proto.EnumName(C2GServiceRegister_MsgID_name, int32(x))
}
func (C2GServiceRegister_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{3, 0} }

type C2GServiceRemove_MsgID int32

const (
	C2GServiceRemove_Zero C2GServiceRemove_MsgID = 0
	C2GServiceRemove_ID   C2GServiceRemove_MsgID = 204
)

var C2GServiceRemove_MsgID_name = map[int32]string{
	0:   "Zero",
	204: "ID",
}
var C2GServiceRemove_MsgID_value = map[string]int32{
	"Zero": 0,
	"ID":   204,
}

func (x C2GServiceRemove_MsgID) String() string {
	return proto.EnumName(C2GServiceRemove_MsgID_name, int32(x))
}
func (C2GServiceRemove_MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{4, 0} }

type Service struct {
	Handler []int32 `protobuf:"varint,1,rep,packed,name=handler" json:"handler,omitempty"`
	Version int32   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Name    string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Address string  `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Service) GetHandler() []int32 {
	if m != nil {
		return m.Handler
	}
	return nil
}

func (m *Service) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// service 2 center server 注册
type S2CServiceRegister struct {
	Serv *Service `protobuf:"bytes,1,opt,name=serv" json:"serv,omitempty"`
}

func (m *S2CServiceRegister) Reset()                    { *m = S2CServiceRegister{} }
func (m *S2CServiceRegister) String() string            { return proto.CompactTextString(m) }
func (*S2CServiceRegister) ProtoMessage()               {}
func (*S2CServiceRegister) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *S2CServiceRegister) GetServ() *Service {
	if m != nil {
		return m.Serv
	}
	return nil
}

// center 2 service 注册结果
type C2SServiceRegisterResult struct {
	Result string `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *C2SServiceRegisterResult) Reset()                    { *m = C2SServiceRegisterResult{} }
func (m *C2SServiceRegisterResult) String() string            { return proto.CompactTextString(m) }
func (*C2SServiceRegisterResult) ProtoMessage()               {}
func (*C2SServiceRegisterResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *C2SServiceRegisterResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// center 2 gateway 注册 service,广播
type C2GServiceRegister struct {
	Serv *Service `protobuf:"bytes,1,opt,name=serv" json:"serv,omitempty"`
}

func (m *C2GServiceRegister) Reset()                    { *m = C2GServiceRegister{} }
func (m *C2GServiceRegister) String() string            { return proto.CompactTextString(m) }
func (*C2GServiceRegister) ProtoMessage()               {}
func (*C2GServiceRegister) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *C2GServiceRegister) GetServ() *Service {
	if m != nil {
		return m.Serv
	}
	return nil
}

// center2 gateway 删除service ,广播
type C2GServiceRemove struct {
	Serv *Service `protobuf:"bytes,1,opt,name=serv" json:"serv,omitempty"`
}

func (m *C2GServiceRemove) Reset()                    { *m = C2GServiceRemove{} }
func (m *C2GServiceRemove) String() string            { return proto.CompactTextString(m) }
func (*C2GServiceRemove) ProtoMessage()               {}
func (*C2GServiceRemove) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *C2GServiceRemove) GetServ() *Service {
	if m != nil {
		return m.Serv
	}
	return nil
}

type RPCRequest struct {
	Userid    uint64 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Messageid int32  `protobuf:"varint,2,opt,name=messageid" json:"messageid,omitempty"`
	Body      []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *RPCRequest) Reset()                    { *m = RPCRequest{} }
func (m *RPCRequest) String() string            { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()               {}
func (*RPCRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *RPCRequest) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *RPCRequest) GetMessageid() int32 {
	if m != nil {
		return m.Messageid
	}
	return 0
}

func (m *RPCRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type RPCResponse struct {
	Response []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (m *RPCResponse) Reset()                    { *m = RPCResponse{} }
func (m *RPCResponse) String() string            { return proto.CompactTextString(m) }
func (*RPCResponse) ProtoMessage()               {}
func (*RPCResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *RPCResponse) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "protocol.Service")
	proto.RegisterType((*S2CServiceRegister)(nil), "protocol.S2CServiceRegister")
	proto.RegisterType((*C2SServiceRegisterResult)(nil), "protocol.C2SServiceRegisterResult")
	proto.RegisterType((*C2GServiceRegister)(nil), "protocol.C2GServiceRegister")
	proto.RegisterType((*C2GServiceRemove)(nil), "protocol.C2GServiceRemove")
	proto.RegisterType((*RPCRequest)(nil), "protocol.RPCRequest")
	proto.RegisterType((*RPCResponse)(nil), "protocol.RPCResponse")
	proto.RegisterEnum("protocol.S2CServiceRegister_MsgID", S2CServiceRegister_MsgID_name, S2CServiceRegister_MsgID_value)
	proto.RegisterEnum("protocol.C2SServiceRegisterResult_MsgID", C2SServiceRegisterResult_MsgID_name, C2SServiceRegisterResult_MsgID_value)
	proto.RegisterEnum("protocol.C2GServiceRegister_MsgID", C2GServiceRegister_MsgID_name, C2GServiceRegister_MsgID_value)
	proto.RegisterEnum("protocol.C2GServiceRemove_MsgID", C2GServiceRemove_MsgID_name, C2GServiceRemove_MsgID_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GatewayCallService service

type GatewayCallServiceClient interface {
	Request(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error)
}

type gatewayCallServiceClient struct {
	cc *grpc.ClientConn
}

func NewGatewayCallServiceClient(cc *grpc.ClientConn) GatewayCallServiceClient {
	return &gatewayCallServiceClient{cc}
}

func (c *gatewayCallServiceClient) Request(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error) {
	out := new(RPCResponse)
	err := grpc.Invoke(ctx, "/protocol.GatewayCallService/Request", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GatewayCallService service

type GatewayCallServiceServer interface {
	Request(context.Context, *RPCRequest) (*RPCResponse, error)
}

func RegisterGatewayCallServiceServer(s *grpc.Server, srv GatewayCallServiceServer) {
	s.RegisterService(&_GatewayCallService_serviceDesc, srv)
}

func _GatewayCallService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayCallServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GatewayCallService/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayCallServiceServer).Request(ctx, req.(*RPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayCallService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.GatewayCallService",
	HandlerType: (*GatewayCallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _GatewayCallService_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x6b, 0xc2, 0x40,
	0x10, 0xc5, 0x5d, 0x8d, 0x46, 0x47, 0x0b, 0x76, 0x69, 0x4b, 0x90, 0x1e, 0xc2, 0x42, 0xc1, 0x5e,
	0x3c, 0xa4, 0x97, 0xde, 0x23, 0x88, 0x87, 0x4a, 0x59, 0x69, 0x0b, 0xbd, 0xad, 0x66, 0xb0, 0xa1,
	0x31, 0x6b, 0x77, 0xa2, 0xc5, 0x8f, 0xd8, 0x3f, 0x1f, 0xaa, 0x64, 0x4d, 0x6a, 0x11, 0x7a, 0x6a,
	0x4f, 0x99, 0xf7, 0xde, 0xf2, 0xdb, 0xb7, 0x4c, 0xe0, 0x88, 0xd0, 0x6c, 0xe2, 0x39, 0x0e, 0x56,
	0x46, 0x67, 0x9a, 0x37, 0xed, 0x67, 0xae, 0x13, 0xf1, 0x0c, 0xee, 0x74, 0x17, 0x71, 0x0f, 0xdc,
	0x27, 0x95, 0x46, 0x09, 0x1a, 0x8f, 0xf9, 0xb5, 0x7e, 0x5d, 0x96, 0x32, 0x4f, 0x36, 0x68, 0x28,
	0xd6, 0xa9, 0x57, 0xf5, 0x59, 0x9e, 0x14, 0x92, 0x73, 0x70, 0x52, 0xb5, 0x44, 0xaf, 0xe6, 0xb3,
	0x7e, 0x4b, 0xda, 0x39, 0x3f, 0xad, 0xa2, 0xc8, 0x20, 0x91, 0xe7, 0x58, 0xbb, 0x94, 0xe2, 0x01,
	0xf8, 0x34, 0x08, 0x8b, 0xfb, 0x24, 0x2e, 0x62, 0xca, 0xd0, 0xf0, 0x0b, 0x70, 0xf2, 0x76, 0x1e,
	0xf3, 0x59, 0xbf, 0x1d, 0x1c, 0x0f, 0xca, 0x6e, 0x83, 0xf2, 0xa0, 0x8d, 0x45, 0x0f, 0xea, 0x37,
	0xb4, 0x18, 0x0f, 0x79, 0x13, 0x9c, 0x47, 0x34, 0xba, 0x5b, 0xe1, 0x2e, 0x54, 0xc7, 0xc3, 0xee,
	0x1b, 0x13, 0x13, 0xf0, 0xc2, 0x60, 0x7a, 0x00, 0x96, 0x48, 0xeb, 0x24, 0xe3, 0x67, 0xd0, 0xd8,
	0x4d, 0xf6, 0x82, 0x96, 0x2c, 0xd4, 0xef, 0xbc, 0x77, 0x96, 0x17, 0x0d, 0x83, 0xd1, 0x7f, 0x17,
	0xfd, 0x60, 0xe2, 0x0e, 0xba, 0x3f, 0xc1, 0x4b, 0xbd, 0xc1, 0x3f, 0x63, 0x3f, 0x99, 0xb8, 0x07,
	0x90, 0xb7, 0xa1, 0xc4, 0x97, 0x35, 0x92, 0x7d, 0xf1, 0x9a, 0xd0, 0xc4, 0x91, 0x45, 0x3a, 0xb2,
	0x50, 0xfc, 0x1c, 0x5a, 0x4b, 0x24, 0x52, 0x0b, 0x8c, 0xa3, 0x62, 0x91, 0x7b, 0x23, 0x5f, 0xe5,
	0x4c, 0x47, 0x5b, 0xbb, 0xca, 0x8e, 0xb4, 0xb3, 0xb8, 0x84, 0xb6, 0xe5, 0xd2, 0x4a, 0xa7, 0x84,
	0xbc, 0x07, 0x4d, 0x53, 0xcc, 0x16, 0xdd, 0x91, 0xdf, 0x3a, 0x98, 0x00, 0x1f, 0xa9, 0x0c, 0x5f,
	0xd5, 0x36, 0x54, 0x49, 0x52, 0xfe, 0x53, 0xd7, 0xe0, 0x96, 0xad, 0x4e, 0xf6, 0x0f, 0xdb, 0x77,
	0xed, 0x9d, 0x1e, 0xb8, 0x3b, 0x9a, 0xa8, 0xcc, 0x1a, 0xd6, 0xbf, 0xfa, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x51, 0xa3, 0x53, 0x23, 0xba, 0x02, 0x00, 0x00,
}
